// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZLhajQSSzD0KcE94Dt9iNE5Gg5AoyYQU',
    appId: '1:72118497644:android:0a52f524e5432e60924349',
    messagingSenderId: '72118497644',
    projectId: 'playpal-b4c30',
    storageBucket: 'playpal-b4c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkUkNYKghZBda8uf1-mdBO4wGzRrt1Ti0',
    appId: '1:72118497644:ios:3968e19f56a274eb924349',
    messagingSenderId: '72118497644',
    projectId: 'playpal-b4c30',
    storageBucket: 'playpal-b4c30.firebasestorage.app',
    androidClientId: '72118497644-8ucgoj62im85vjaesulua9kj9o41g6fp.apps.googleusercontent.com',
    iosClientId: '72118497644-gemutdmnoj3i7pfkkt5rj5rjgal648co.apps.googleusercontent.com',
    iosBundleId: 'com.example.playpal',
  );
}
